dependencies {
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-web'
    implementation 'tools.jackson.core:jackson-databind'
    implementation project(':domain')
    implementation project(':logging')

    compileOnly "org.slf4j:slf4j-api"
    testCompileOnly "org.slf4j:slf4j-api"

    annotationProcessor 'org.projectlombok:lombok'

    testImplementation "org.mockito:mockito-junit-jupiter"
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "org.springframework:spring-test"
    testImplementation testFixtures(project(":domain"))
}